### PR TITLE
fix coverage reports

### PR DESCRIPTION
**Pull request by bjaglin**
Closes https://github.com/liancheng/scalafix-organize-imports/issues/54

### CODE REVIEW

**Comment by bjaglin** [comment]
@liancheng here we go! failure ... expected - I guess it should be merged to master anyway and things will turn green in the next commit/PR?

**Comment by liancheng** [comment]
Hmm, I still didn't see `OrganizeImports.scala` included in the report? The newly included file is:

```
shared/src/main/scala/fix/Implicits.scala
```

The `shared` project is used for testing purposes, and we don't really care about the coverage of this SBT project.

**Comment by liancheng** [comment]
_Maybe_ this issue is related to this one: https://docs.codecov.io/docs/fixing-paths

**Comment by bjaglin** [comment]
oops indeed, I saw code coverage decreased, so I didn't even check... I'll have another look, sorry for the noise

**Comment by liancheng** [comment]
Lol, I would be pretty sad if the test coverage is only around 70%. The last time I checked it, it was above 95%.

**Comment by bjaglin** [comment]
Looking at the raw upload https://codecov.io/codecov/v4/raw/2020-05-29/6B959D8FB7518A1CFF0DF84B926C2924/e9379fbc51d62d1217d50ee4fd3254cd8ea840aa/0f970c5e-e729-4037-a1da-2c3da3158b11.txt, it's clearly related to the filename, which is merely `fix/OrganizeImports.scala`, and exists in other (test) sub-projects. So we could rename the test package to avoid that. I am trying to ignore the test paths to see if that helps.

**Comment by bjaglin** [comment]
I tried `ignore` and `fixes` in `codecov.yml` (see below), but it didn't help (even though `codecov.yml` is detected according to the logs). FWIW, this is what the github action seems to wrap: https://codecov.io/bash.

So I just went for the rename route, which seems to work at least. Another option would be to rename the test input/output package from `fix` to `test` to make sure someone does not introduce a conflict again in the future.

```
ignore:
  - "input*/**/*"
  - "output/**/*"
```

```
fixes:
  - "::rules/src/main/scala/"
```

**Comment by liancheng** [comment]
Awesome! Thanks for looking into this and get it fixed! 🎉

**Comment by liancheng** [comment]
This is the first time I feel glad to see the test coverage dropped 😆

**Pull request merged**
